<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
         http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">


    <modelVersion>4.0.0</modelVersion>



    <groupId>com.dogonoithat</groupId>

    <artifactId>DoGoNoiThat</artifactId>

    <version>1.0-SNAPSHOT</version>


    <packaging>war</packaging>





    <properties>


        <maven.compiler.source>21</maven.compiler.source>

        <maven.compiler.target>21</maven.compiler.target>

        <project.build.sourceEncoding>
            UTF-8
        </project.build.sourceEncoding>


    </properties>


    <dependencies>


        <!-- Servlet Jakarta Tomcat 11 -->

        <dependency>

            <groupId>jakarta.servlet</groupId>

            <artifactId>jakarta.servlet-api</artifactId>

            <version>6.0.0</version>

            <scope>provided</scope>

        </dependency>


        <dependency>
            <groupId>org.mindrot</groupId>
            <artifactId>jbcrypt</artifactId>
            <version>0.4</version>
        </dependency>



        <!-- JSP -->

        <dependency>

            <groupId>jakarta.servlet.jsp</groupId>

            <artifactId>jakarta.servlet.jsp-api</artifactId>

            <version>3.1.1</version>

            <scope>provided</scope>

        </dependency>






        <!-- JSTL -->

        <dependency>

            <groupId>jakarta.servlet.jsp.jstl</groupId>

            <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>

            <version>3.0.0</version>

        </dependency>





        <dependency>

            <groupId>org.glassfish.web</groupId>

            <artifactId>jakarta.servlet.jsp.jstl</artifactId>

            <version>3.0.1</version>

        </dependency>





        <dependency>
            <groupId>io.github.cdimascio</groupId>
            <artifactId>dotenv-java</artifactId>
            <version>3.2.0</version>
        </dependency>

        <!-- MySQL Driver -->


        <dependency>

            <groupId>com.mysql</groupId>

            <artifactId>mysql-connector-j</artifactId>

            <version>8.4.0</version>

        </dependency>






        <!-- Gson nếu -->


        <dependency>

            <groupId>com.google.code.gson</groupId>

            <artifactId>gson</artifactId>

            <version>2.11.0</version>

        </dependency>



    </dependencies>







    <build>


        <finalName>
            DoGoNoiThat
        </finalName>



        <plugins>


            <!-- Maven WAR -->


            <plugin>

                <groupId>
                    org.apache.maven.plugins
                </groupId>


                <artifactId>
                    maven-war-plugin
                </artifactId>


                <version>3.4.0</version>


                <configuration>

                    <failOnMissingWebXml>
                        false
                    </failOnMissingWebXml>

                </configuration>


            </plugin>





            <!-- Java 21 -->


            <plugin>


                <groupId>
                    org.apache.maven.plugins
                </groupId>


                <artifactId>
                    maven-compiler-plugin
                </artifactId>


                <version>3.13.0</version>


                <configuration>


                    <release>
                        21
                    </release>


                    <encoding>
                        UTF-8
                    </encoding>


                </configuration>


            </plugin>



        </plugins>



    </build>



</project>